# Generated by Django 5.0.1 on 2024-01-29 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookapi', '0004_remove_book_author_remove_book_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('released_year', models.DateField()),
                ('copies_available', models.PositiveIntegerField()),
                ('pages', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='Bookapi.author')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library', to='Bookapi.library')),
                ('genre', models.ManyToManyField(to='Bookapi.genre')),
            ],
        ),
    ]
