# Generated by Django 5.0.1 on 2024-02-07 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookapi', '0008_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
    ]
